version: '3.8'

services:
  runner:
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        NODE_MAJOR: '14'
    image: osm-to-geojson-api:0.0.8
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
