version: '3.8'

services:
  runner:
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
    image: osm-to-geojson-api:0.0.2
    volumes:
      - .:/app

  serverless:
    image: serverlesspolska/serverless-framework
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
