service: osm-to-geojson-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  profile: serverless-admin
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  relation-boundary:
    handler: handler.boundary
    events:
      - http:
          cors: true
          path: relation/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  way-boundary:
    handler: handler.boundary
    events:
      - http:
          cors: true
          method: get
          path: way/{id}
          request:
            parameters:
              paths:
                id: true
  node-boundary:
    handler: handler.boundary
    events:
      - http:
          cors: true
          method: get
          path: node/{id}
          request:
            parameters:
              paths:
                id: true

package:
  patterns:
    - alpha_shape.py
    - handler.py
    - osm_site.py
    - wikidata.py
